name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-to-nuget:
    uses: Settlers4-Reforged/S4Forge.SDK/.github/workflows/publish-workflow.yml@main
    with:
      package_name: S4Forge.UX-Engine
    secrets: inherit
  release-package:
    uses: Settlers4-Reforged/S4Forge.SDK/.github/workflows/release-workflow.yml@main
    secrets: inherit
