name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-to-nuget:
    uses: Settlers-4-Reforged/S4Forge.SDK/.github/workflows/publish-workflow.yml@main
    with:
      package_name: S4Forge.UX-Engine
    secrets: inherit
